language: node_js
node_js:
- '12'
sudo: false
branches:
  except:
  - gh-pages
env:
  global:
  - secure: ONfNUHKLNXeG+mqPucbNhXnw7VRmpYKJDXLxyyO1ZxyoSZLytDH9QD3xXLLKwfqVP1DfEAI26xwipGAZejvaXB5Td+a4Q+b3B0Wx0q3kYSh+oQL/CK16HrJkeAbe68hXIYTdRMzQkbwTgDlRbmJiMoNOS6tos6H5dq7V/j5ND60=
after_success:
- cd $TRAVIS_BUILD_DIR
- chmod +x generateDocs.sh
- bash generateDocs.sh
notifications:
  slack:
    secure: tFVXLE/u2iRMk65ghX6vzWz7Xv43Tppq4/Q1z1T1fhs0ZDjjGVFexiap0WbU0VvVo111J5+tW8I/VmtwLpomm5nTTuhFKVjXKbu7qswLn6Jm5cOKGSpGC1kS8RdNbuJVbqAL2WjYeEftBh2Cq8KN0DIcnqz4lYDK2cay6+7mQ/M=
